

### get all
GET  http://localhost:3000/posts

### Get one
GET  http://localhost:3000/posts/2


### Create
POST http://localhost:3000/posts
Content-Type: application/json
# El body - hi ha d'haver un espai a sota

{
    "name": "post"   
}

### Update
PUT http://localhost:3000/posts/1
Content-Type: application/json
# El body - hi ha d'haver un espai a sota

{
    "name": "modificat!"   
}

### Delete
DELETE http://localhost:3000/posts/5